#!/bin/bash
if [[ -z $1 ]]; then
  echo "Usage: scripts/compare FILE.yml"
  exit 1
fi

rm -rf tmp

echo
echo "========== JJB ==========="
jenkins-jobs test $1 -o tmp/jjb

echo
echo "========= Cigale ========="
cigale test $1 -o tmp/cigale

echo
echo "====== Comparison ========"
git diff --exit-code --word-diff --no-index --color=always tmp/{jjb,cigale} && echo "Same!"
