#!/bin/bash -e

if [[ -z $1 ]]; then
  echo "Usage: scripts/compare FILE.yml"
  exit 1
fi

rm -rf tmp
jenkins-jobs -l ERROR test $1 -o tmp/jjb
cigale -l ERROR test $1 -o tmp/cigale
git diff --exit-code --word-diff --no-index --color=always tmp/{jjb,cigale}
